### ISSUE TITLE
Downloaded models folder is not created and crash in Windows

### ISSUE THREAD

**Issue by arpinerap** [lassoan/SlicerMONAIAuto3DSeg#1]
Folder ".MONAIAuto3DSeg" is not created, or not allowed to create, and download task fail.

**Comment by lassoan** [comment]
Thane for reporting, the issue has been fixed earlier today. You can get the updates from this repository now or update the extension tomorrow in the Extensions Manager.

**Comment by rbumm** [comment]
I have just tested again:with a newly downloaded extension.
It extracted the models fine,
But still got the

[image: image.png]

Python 3.9.10 (main, Dec 12 2023, 02:25:18) [MSC v.1935 64 bit (AMD64)] on
win32

>>>

WARNING: Ignoring invalid distribution -illow (c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages)

Requirement already satisfied:
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm] in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (0.4.0)

WARNING: monai 0.4.0 does not provide the extra 'fire'

WARNING: monai 0.4.0 does not provide the extra 'pynrrd'

WARNING: monai 0.4.0 does not provide the extra 'pyyaml'

Requirement already satisfied: torch>=1.5 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.13.1)

Requirement already satisfied: numpy>=1.17 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.26.1)

Requirement already satisfied: nibabel in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.2.0)

Requirement already satisfied: psutil in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.9.6)

Requirement already satisfied: tensorboard in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.15.1)

Requirement already satisfied: scikit-image>=0.14.2 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.22.0)

Requirement already satisfied: tqdm>=4.47.0 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(4.66.1)

Requirement already satisfied: itk in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: scipy>=1.8 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.11.3)

Requirement already satisfied: networkx>=2.8 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.2.1)

Requirement already satisfied: pillow>=9.0.1 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(10.0.1)

Requirement already satisfied: imageio>=2.27 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.33.1)

Requirement already satisfied: tifffile>=2022.8.12 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2023.12.9)

Requirement already satisfied: packaging>=21 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(23.2)

Requirement already satisfied: lazy_loader>=0.3 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
scikit-image>=0.14.2->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.3)

Requirement already satisfied: typing-extensions in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
torch>=1.5->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(4.8.0)

Requirement already satisfied: colorama in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
tqdm>=4.47.0->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.4.6)

Requirement already satisfied: itk-core==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: itk-numerics==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: itk-io==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: itk-filtering==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: itk-registration==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: itk-segmentation==5.3.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
itk->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.0)

Requirement already satisfied: absl-py>=0.4 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.0.0)

Requirement already satisfied: grpcio>=1.48.2 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.60.0)

Requirement already satisfied: google-auth<3,>=1.6.3 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.26.2)

Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.2.0)

Requirement already satisfied: markdown>=2.6.8 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.5.2)

Requirement already satisfied: protobuf<4.24,>=3.19.6 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(4.23.4)

Requirement already satisfied: requests<3,>=2.21.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.31.0)

Requirement already satisfied: setuptools>=41.0.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(68.2.2)

Requirement already satisfied: six>1.9 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.16.0)

Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.7.2)

Requirement already satisfied: werkzeug>=1.0.1 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.0.1)

Requirement already satisfied: cachetools<6.0,>=2.0.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(5.3.2)

Requirement already satisfied: pyasn1-modules>=0.2.1 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.3.0)

Requirement already satisfied: rsa<5,>=3.1.4 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
google-auth<3,>=1.6.3->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(4.9)

Requirement already satisfied: requests-oauthlib>=0.7.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
google-auth-oauthlib<2,>=0.5->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(1.3.1)

Requirement already satisfied: importlib-metadata>=4.4 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
markdown>=2.6.8->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(7.0.1)

Requirement already satisfied: charset-normalizer<4,>=2 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
requests<3,>=2.21.0->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.3.0)

Requirement already satisfied: idna<4,>=2.5 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
requests<3,>=2.21.0->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.4)

Requirement already satisfied: urllib3<3,>=1.21.1 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
requests<3,>=2.21.0->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.0.6)

Requirement already satisfied: certifi>=2017.4.17 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
requests<3,>=2.21.0->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2023.7.22)

Requirement already satisfied: MarkupSafe>=2.1.1 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
werkzeug>=1.0.1->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(2.1.3)

Requirement already satisfied: zipp>=0.5 in c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages (from
importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.17.0)

Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(0.5.1)

Requirement already satisfied: oauthlib>=3.0.0 in
c:\users\rudol\appdata\local\slicer.org\slicer
5.6.1\lib\python\lib\site-packages (from
requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard->monai[fire,itk,nibabel,psutil,pynrrd,pyyaml,skimage,tensorboard,tqdm])
(3.2.2)

WARNING: Ignoring invalid distribution -illow (c:\users\rudol\appdata\local\
slicer.org\slicer 5.6.1\lib\python\lib\site-packages)

[Python] Failed to compute results.

[Python] Command '['C:/Users/rudol/AppData/Local/slicer.org/Slicer
5.6.1/bin/../bin\\PythonSlicer.EXE', '-m', 'monai.apps.auto3dseg',
'AutoRunner', 'run', '--input',
'C:\\Users\\rudol\\.MONAIAuto3DSeg\\models\\17-segments-TotalSegmentator-v2\\input.yaml',
'--work_dir',
'C:\\Users\\rudol\\.MONAIAuto3DSeg\\models\\17-segments-TotalSegmentator-v2',
'--algos', 'segresnet', '--train=False', '--analyze=False',
'--ensemble=True']' returned non-zero exit status 1.

Traceback (most recent call last):

File
"C:/Users/rudol/OneDrive/Dokumente/MySlicerExtensions/SlicerMONAIAuto3DSeg-main/SlicerMONAIAuto3DSeg-main/MONAIAuto3DSeg/MONAIAuto3DSeg.py",
line 296, in onApplyButton

self.logic.process(self.ui.inputVolumeSelector.currentNode(),
self.ui.outputSegmentationSelector.currentNode(),

File
"C:/Users/rudol/OneDrive/Dokumente/MySlicerExtensions/SlicerMONAIAuto3DSeg-main/SlicerMONAIAuto3DSeg-main/MONAIAuto3DSeg/MONAIAuto3DSeg.py",
line 780, in process

self.logProcessOutput(proc)

File
"C:/Users/rudol/OneDrive/Dokumente/MySlicerExtensions/SlicerMONAIAuto3DSeg-main/SlicerMONAIAuto3DSeg-main/MONAIAuto3DSeg/MONAIAuto3DSeg.py",
line 671, in logProcessOutput

raise CalledProcessError(retcode, proc.args, output=proc.stdout,
stderr=proc.stderr)

subprocess.CalledProcessError: Command '['C:/Users/rudol/AppData/Local/
slicer.org/Slicer 5.6.1/bin/../bin\\PythonSlicer.EXE', '-m',
'monai.apps.auto3dseg', 'AutoRunner', 'run', '--input',
'C:\\Users\\rudol\\.MONAIAuto3DSeg\\models\\17-segments-TotalSegmentator-v2\\input.yaml',
'--work_dir',
'C:\\Users\\rudol\\.MONAIAuto3DSeg\\models\\17-segments-TotalSegmentator-v2',
'--algos', 'segresnet', '--train=False', '--analyze=False',
'--ensemble=True']' returned non-zero exit status 1.



The model folder on my home file looks like this:


[image: image.png]

[image: image.png]

[image: image.png]


I will be traveling to Chur tomorrow and return on Friday, could do tests
in the evening or on Saturday.


Best

Rudolf






Am Mi., 17. Jan. 2024 um 21:46 Uhr schrieb Andras Lasso <
***@***.***>:

**Comment by diazandr3s** [comment]
Hi @rbumm,

I can't see the images you're referring to. It seems there was an error when uploading them.
Can you please upload them again?

Thanks!

**Comment by lassoan** [comment]
Monai install is not related to this problem ("Downloaded models folder is not created and crash in Windows"). I'll move it to a new issue.
