### ISSUE TITLE
ITK error

### ISSUE THREAD

**Issue by mauigna06** [lassoan/SlicerMONAIAuto3DSeg#24]
Testing this extension with 3 different CBCTs, the following errors occurred on the first two:

![Screenshot from 2024-02-27 09-09-12](https://github.com/lassoan/SlicerMONAIAuto3DSeg/assets/19158307/72364b13-3368-4360-b846-2f278d40325e)

![Screenshot from 2024-02-27 09-13-49](https://github.com/lassoan/SlicerMONAIAuto3DSeg/assets/19158307/7d7143e2-d3dd-454d-ad47-fafaed02ac2c)

I think the problem may be related to fact that the vectors of the ijk2ras matrix are not orthonormal

![Screenshot from 2024-02-27 10-08-33](https://github.com/lassoan/SlicerMONAIAuto3DSeg/assets/19158307/2d88f972-b94b-46b2-978a-07c0d07f9283)

This comment looked as the exact solution (but it did not work):
https://github.com/wasserth/TotalSegmentator/blob/master/README.md#typical-problems

@lassoan :)

**Comment by lassoan** [comment]
We should just get rid of NIFTI and save as NRRD instead.
