### ISSUE TITLE
Support multiple input volumes

### ISSUE THREAD

**Issue by che85** [lassoan/SlicerMONAIAuto3DSeg#25]
Some models are trained using multiple input images (e.g. https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg/tasks/hecktor22)

Selectors could be dynamically created when segmentation model is selected.

**Comment by diazandr3s** [comment]
Hi @che85,

Thanks for opening this issue.
I've updated the inference script here: https://github.com/lassoan/SlicerMONAIAuto3DSeg/pull/29
We'll be working on the UI part so it sends a dictionary with the image paths.
