### ISSUE TITLE
Display progress information

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerMONAIAuto3DSeg#4]
During inference, the model may not provide any updates for minutes and the user does not know if he just needs to wait a little more or much-much longer.

Therefore, it would be important to provide an update to the user (new progress percentage) at least in every 5-10 seconds.

**Comment by diazandr3s** [comment]
Proposed solution: https://github.com/lassoan/SlicerMONAIAuto3DSeg/pull/6
