### ISSUE TITLE
Improve accuracy

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerMONAIAuto3DSeg#5]
If providing models that have similar scope as TotalSegmentator (segmenting organs, bones, vessels in CT) then it would be important to at least match the quality of TotalSegmentator output. For images where original TS training data does not contain all segments then TS output could be used as training.

**Comment by diazandr3s** [comment]
Please test the update version. Inference script updated to improve accuracy: https://github.com/lassoan/SlicerMONAIAuto3DSeg/pull/8

**Comment by lassoan** [comment]
From @rbumm:

> Just tested the new version, and the progress is amazing. 
Excellent work ...
