### ISSUE TITLE
Intracranial bleeding models not listed

### ISSUE THREAD

**Issue by smcch** [lassoan/SlicerMONAIAuto3DSeg#58]
I can't find intracranial bleeding models in 'Segmentation model' list. 

Thanks!

**Comment by diazandr3s** [comment]
Hi @smcch,

Can you please confirm which Slicer version you are using? Could you please try the latest Preview version and install the Auto3DSeg?

Let us know,

**Comment by smcch** [comment]
After installing the latest version the error has been corrected. Thanks!
