### ISSUE TITLE
Export for high quality 3d printing?

### ISSUE THREAD

**Issue by yanfeiwong** [lassoan/SlicerMONAIAuto3DSeg#82]
Hi, wondering how to export better mesh instead of rasterized results? The render from 'Colorized Volume' looks pretty amazing, but I guess its not for export?

**Comment by lassoan** [comment]
If you have a color raster 3D printer then you can print the colorized volume as is (see https://github.com/SlicerFab/SlicerFab).

If your printer can only accept a colored mesh as input then there is not much you can do. A surface mesh only contains information about an infinitely thin layer, no subsurface information, so you will not be able to see the same thing as with volume rendering.

**Comment by yanfeiwong** [comment]
> If you have a color raster 3D printer then you can print the colorized volume as is (see https://github.com/SlicerFab/SlicerFab).
> 
> If your printer can only accept a colored mesh as input then there is not much you can do. A surface mesh only contains information about an infinitely thin layer, no subsurface information, so you will not be able to see the same thing as with volume rendering.

I was actually hoping for a way or a semi auto way to refine the AI segmented result, It could be really helpful..
