### ISSUE TITLE
Where to download the model file

### ISSUE THREAD

**Issue by ZHUJJFDU** [lassoan/SlicerMONAIAuto3DSeg#83]
When i open up https://github.com/lassoan/SlicerMONAIAuto3DSeg/releases/download/Models/ it seams that there is no such page. Can you tell me where to download the model file?

**Comment by lassoan** [comment]
You can find all releases assets by clicking on on "Releases". Direct link: https://github.com/lassoan/SlicerMONAIAuto3DSeg/releases/tag/Models

**Comment by rbumm** [comment]
This happens all automatically when you have installed the extension. You can select the model from the GUISent from my iPhoneOn 16. Oct 2024, at 09:42, ZHUJJFDU ***@***.***> wrote:﻿
When i open up https://github.com/lassoan/SlicerMONAIAuto3DSeg/releases/download/Models/ it seams that there is no such page. Can you tell me where to download the model file?
