### ISSUE TITLE
a Big Error about SlicerMONAIAuto3DSeg

### ISSUE THREAD

**Issue by yankun2024** [lassoan/SlicerMONAIAuto3DSeg#84]
Traceback (most recent call last):
  File "C:/ProgramData/slicer.org/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 47, in configureDefaultTerminology
    tlogic = slicer.modules.terminologies.logic()
AttributeError: module 'modules' has no attribute 'terminologies'

**Comment by yankun2024** [comment]
The situation is as follows: 

1. I downloaded Slicer from https://download.slicer.org/ on a completely clean Windows device; 
2. Then I selected Preview Release and installed SlicerMONAIAuto3DSeg from the extension manager, but got an error after restarting; 
3. Then I downloaded the Stable Release and encountered the same issue.

**Comment by lassoan** [comment]
See the solution here: https://github.com/lassoan/SlicerMONAIAuto3DSeg?tab=readme-ov-file#troubleshooting

**Comment by lassoan** [comment]
I see that you provided a little detail (`AttributeError: module 'modules' has no attribute 'terminologies'`) - I'll check if I can give you more specific recommendations based on that.

**Comment by lassoan** [comment]
What happens if you type `slicer.modules.terminologies.logic()` into the Python console in Slicer? Do you see any error messages?

**Comment by lassoan** [comment]
If you see any error then most likely one of the extensions or custom modules corrupts your Slicer installation. What other extensions have you installed? Have you tried to add some custom modules? Could you provide the whole application log (menu: Help / Report a bug)?

**Comment by yankun2024** [comment]
> What happens if you type `slicer.modules.terminologies.logic()` into the Python console in Slicer? Do you see any error messages?如果您在 Slicer 的 Python 控制台中键入 `slicer.modules.terminologies.logic()` 内容，会发生什么情况？您是否看到任何错误消息？

yes. no terminologies，It still is the same.

**Comment by yankun2024** [comment]
> If you see any error then most likely one of the extensions or custom modules corrupts your Slicer installation. What other extensions have you installed? Have you tried to add some custom modules? Could you provide the whole application log (menu: Help / Report a bug)?如果您看到任何错误，则很可能是某个扩展或自定义模块损坏了您的 Slicer 安装。您还安装了哪些其他扩展？您是否尝试过添加一些自定义模块？您能否提供完整的应用程序日志（菜单：帮助 / 报告错误）？

There is no 'Terminologies' in the 'Module Finder'.  I haven't installed any third-party modules; the entire Slicer is freshly installed.

**Comment by lassoan** [comment]
Could you provide the whole application log (menu: Help / Report a bug)?

**Comment by yankun2024** [comment]
> slicer.modules.terminologies.logic()

[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Session start time .......: 20241018_111736
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Slicer version ...........: 5.6.2 (revision 32448 / f10cd8c) win-amd64 - installed release
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Operating system .........: Windows /  Professional / (Build 19045, Code Page 65001) - 64-bit
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Memory ...................: 64667 MB physical, 68763 MB virtual
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - CPU ......................: AuthenticAMD AMD Ryzen 9 7950X 16-Core Processor            , 32 cores, 32 logical processors
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Developer mode ...........: enabled
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Application path .........: D:/Slicer 5.6.2/bin
[DEBUG][Qt] 18.10.2024 11:17:36 [] (unknown:0) - Additional module paths ..: slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules, slicer.org/Extensions-32448/PyTorch/lib/Slicer-5.6/qt-scripted-modules
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "DICOM" , the dependency "SubjectHierarchy" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "DICOM" , the dependency "SubjectHierarchy" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "DICOMPatcher" , the dependency "DICOM" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "Endoscopy" , the dependency "Markups" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "MultiVolumeImporter" , the dependency "MultiVolumeExplorer" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "NeurosurgicalPlanningTutorialMarkupsSelfTest" , the dependency "Segmentations" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "PlotsSelfTest" , the dependency "Plots" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "SegmentEditor" , the dependency "Segmentations" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "SegmentStatistics" , the dependency "SubjectHierarchy" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "SequencesSelfTest" , the dependency "Sequences" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "SubjectHierarchyCorePluginsSelfTest" , the dependency "SubjectHierarchy" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "SubjectHierarchyGenericSelfTest" , the dependency "SubjectHierarchy" failed to be loaded.
[WARNING][Qt] 18.10.2024 11:17:37 [] (unknown:0) - When loading module  "TablesSelfTest" , the dependency "Tables" failed to be loaded.
[CRITICAL][Stream] 18.10.2024 11:17:37 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 18.10.2024 11:17:37 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 47, in configureDefaultTerminology
[CRITICAL][Stream] 18.10.2024 11:17:37 [] (unknown:0) -     tlogic = slicer.modules.terminologies.logic()
[CRITICAL][Stream] 18.10.2024 11:17:37 [] (unknown:0) - AttributeError: module 'modules' has no attribute 'terminologies'
[DEBUG][Qt] 18.10.2024 11:17:44 [] (unknown:0) - Switch to module:  "MONAIAuto3DSeg"
[DEBUG][Qt] 18.10.2024 11:17:44 [] (unknown:0) - The module "Terminologies" has not been registered.
[DEBUG][Qt] 18.10.2024 11:17:44 [] (unknown:0) - The following modules have been registered: ("AddManyMarkupsFiducialTest", "AddScalarVolumes", "AtlasTests", "BRAINSDWICleanup", "BRAINSDeface", "BRAINSFit", "BRAINSFitRigidRegistrationCrashIssue4139", "BRAINSIntensityNormalize", "BRAINSROIAuto", "BRAINSResample", "BRAINSResize", "BRAINSStripRotation", "BRAINSTransformConvert", "CastScalarVolume", "CheckerBoardFilter", "ColorLegendSelfTest", "CompareVolumes", "CreateDICOMSeries", "CropVolumeSelfTest", "CropVolumeSequence", "CurvatureAnisotropicDiffusion", "DICOM", "DICOMEnhancedUSVolumePlugin", "DICOMGeAbusPlugin", "DICOMImageSequencePlugin", "DICOMPatcher", "DICOMScalarVolumePlugin", "DICOMSlicerDataBundlePlugin", "DICOMVolumeSequencePlugin", "DMRIInstall", "DWIConvert", "DataProbe", "Decimation", "Endoscopy", "EventBroker", "ExecutionModelTour", "ExtensionWizard", "ExtractSkeleton", "FiducialLayoutSwitchBug1914", "FiducialRegistration", "GaussianBlurImageFilter", "GradientAnisotropicDiffusion", "GrayscaleFillHoleImageFilter", "GrayscaleGrindPeakImageFilter", "GrayscaleModelMaker", "HistogramMatching", "ImageLabelCombine", "ImportItkSnapLabel", "JRC2013Vis", "LabelMapSmoothing", "LandmarkRegistration", "MONAIAuto3DSeg", "MarkupsInCompareViewersSelfTest", "MarkupsInViewsSelfTest", "MaskScalarVolume", "MedianImageFilter", "MergeModels", "ModelMaker", "ModelToLabelMap", "MultiVolumeImporter", "MultiVolumeImporterPlugin", "MultiplyScalarVolumes", "N4ITKBiasFieldCorrection", "NeurosurgicalPlanningTutorialMarkupsSelfTest", "OrientScalarVolume", "PETStandardUptakeValueComputation", "PerformMetricTest", "PerformanceTests", "PlotsSelfTest", "PluggableMarkupsSelfTest", "ProbeVolumeWithModel", "PyTorchUtils", "RSNA2012ProstateDemo", "RSNAQuantTutorial", "RSNAVisTutorial", "ResampleDTIVolume", "ResampleScalarVectorDWIVolume", "ResampleScalarVolume", "RobustStatisticsSegmenter", "SampleData", "ScenePerformance", "ScreenCapture", "SegmentEditor", "SegmentStatistics", "SelfTests", "SequencesSelfTest", "ShaderProperties", "SimpleFilters", "SimpleRegionGrowingSegmentation", "SliceLinkLogic", "Slicer4Minute", "SlicerBoundsTest", "SlicerDisplayNodeSequenceTest", "SlicerMRBMultipleSaveRestoreLoopTest", "SlicerMRBMultipleSaveRestoreTest", "SlicerMRBSaveRestoreCheckPathsTest", "SlicerOrientationSelectorTest", "SlicerScriptedFileReaderWriterTest", "SlicerTransformInteractionTest1", "SubjectHierarchyCorePluginsSelfTest", "SubjectHierarchyGenericSelfTest", "SubtractScalarVolumes", "SurfaceToolbox", "TablesSelfTest", "ThresholdScalarVolume", "UtilTest", "VectorToScalarVolume", "ViewControllersSliceInterpolationBug1926", "VolumeRenderingSceneClose", "VotingBinaryHoleFillingImageFilter", "WebEngine", "WebServer", "sceneImport2428")
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 210, in setup
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     self.logic = MONAIAuto3DSegLogic()
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 667, in __init__
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     self.MONAIAuto3DSegTerminologyPropertyTypes = self._MONAIAuto3DSegTerminologyPropertyTypes()
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 852, in _MONAIAuto3DSegTerminologyPropertyTypes
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     terminologiesLogic = slicer.util.getModuleLogic("Terminologies")
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:\Slicer 5.6.2\bin\Python\slicer\util.py", line 1334, in getModuleLogic
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     module = getModule(module)
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:\Slicer 5.6.2\bin\Python\slicer\util.py", line 1252, in getModule
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     raise RuntimeError("Could not find module with name '%s'" % moduleName)
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) - RuntimeError: Could not find module with name 'Terminologies'
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 263, in enter
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     self.initializeParameterNode()
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -   File "D:/Slicer 5.6.2/slicer.org/Extensions-32448/MONAIAuto3DSeg/lib/Slicer-5.6/qt-scripted-modules/MONAIAuto3DSeg.py", line 294, in initializeParameterNode
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) -     self.setParameterNode(self.logic.getParameterNode())
[CRITICAL][Stream] 18.10.2024 11:17:44 [] (unknown:0) - AttributeError: 'NoneType' object has no attribute 'getParameterNode'

**Comment by yankun2024** [comment]
I ensured that I installed Slicer correctly, and there were no errors during the installation process. The entire installation directory contains 8,848 files and is about 960 MB in size.

**Comment by yankun2024** [comment]
![image](https://github.com/user-attachments/assets/7dcb314b-94cc-4b14-8cec-0a0583113e9c)
I had been paying attention to this extension error before, and now I feel it's more like a loading error within Slicer itself.

**Comment by yankun2024** [comment]
> I ensured that I installed Slicer correctly, and there were no errors during the installation process. The entire installation directory contains 8,848 files and is about 960 MB in size.

i compress the entire installation directory and transfer it to other devices ，is ok, it may be related to the system.?

**Comment by lassoan** [comment]
The problem is that Slicer core modules are not found.

Installing Slicer on a computer and then copying the entire installation tree to another computer should work well. However, you maybe some errors occurred while you copied the files. Check if you have the exact same files on the new computer after copying.

Please try to install the latest MSVC redistributable package from here:  https://aka.ms/vs/17/release/vc_redist.x64.exe

If that does not help then check if you have any third-party anti-virus software and if that may have interfered with installation and execution of the software. Probably the anti-virus software has an action log that you can inspect.
