### ISSUE TITLE
Not all models showing after installing plugin

### ISSUE THREAD

**Issue by wmccuddy** [lassoan/SlicerMONAIAuto3DSeg#89]
Using Slicer 5.6.1 on windows, I installed MONAIAuto3DSeg from Slicer Extension Manager. After restarting slicer and selecting the MONAI module, various models show in the Segmentation model selection dropdown, but the BRATS models were not there. 
![image](https://github.com/user-attachments/assets/c6641fdf-c521-48a3-a8cc-3e092232f700)

**Comment by lassoan** [comment]
You always need to use the latest Slicer Stable Release or latest Slicer Preview Release.
